---
# RedHat_install_epel-release/tasks/main.yml

- name: 'Check if codeready-builder-for-rhel-8 repository is enabled already'
  shell:
    cmd: "LANG=C subscription-manager repos|grep -A 3 codeready-builder-for-rhel-8-{{ ansible_architecture }}-rpms|grep '^Enabled.*$'"
  register: subscription_manager_output
  check_mode: 'false'

- name: 'Debug: Output variable subscription_manager_output'
  debug:
   var: subscription_manager_output

- name: 'install epel-release key via https'
  rpm_key:
    key: 'https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}'
    state: 'present'
  when: 'ansible_distribution == "RedHat"'
  ignore_errors: "{{ ansible_check_mode |default(false)}}"

- name: 'Enable the codeready-builder-for-rhel-8 repository'
  shell:
    cmd: 'subscription-manager repos --enable codeready-builder-for-rhel-8-$(arch)-rpms'
  when:
    - 'ansible_distribution == "RedHat"'
    - 'ansible_distribution_major_version == "8"'
    - '"0" in subscription_manager_output.stdout'

- name: 'install package epel-release'
  package:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: 'present'
  when: 'ansible_distribution == "RedHat"'
  ignore_errors: "{{ ansible_check_mode |default(false)}}"
  notify:
    - "run 'yum makecache fast'"
    - "run 'dnf makecache'"

- name: 'install epel-release key from /etc/pki/rpm-gpg/'
  rpm_key:
    key: '/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}'
    state: 'present'
  when: 'ansible_distribution == "RedHat"'
  ignore_errors: "{{ ansible_check_mode |default(false)}}"

- meta: flush_handlers
