---
# RedHat_install_epel-release/tasks/main.yml

- name: 'Check if codeready-builder-for-rhel-X repository is enabled already'
  ansible.builtin.shell:
    cmd: >
      LANG=C subscription-manager repos|grep -A 3
      codeready-builder-for-rhel-{{ ansible_distribution_major_version | int }}-{{ ansible_architecture }}-rpms
      | grep '^Enabled.*$'
  register: subscription_manager_output
  check_mode: 'false'
  changed_when: 'false'
  when:
    - 'ansible_distribution == "RedHat"'
    - 'ansible_distribution_major_version | int == 8 or ansible_distribution_major_version | int == 9'

- name: 'Debug: Output variable subscription_manager_output'
  ansible.builtin.debug:
    var: subscription_manager_output
  when:
    - 'ansible_distribution == "RedHat"'

- name: 'Install epel-release key via https'
  ansible.builtin.rpm_key:
    key: 'https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}'
    state: 'present'
  when:
    - 'ansible_distribution == "RedHat"'

- name: 'Enable the codeready-builder-for-rhel-X repository'
  ansible.builtin.shell:
    cmd: 'subscription-manager repos --enable codeready-builder-for-rhel-{{ ansible_distribution_major_version | int }}-$(arch)-rpms'
  # Shell tasks do always show up as changed, and ansible-lint complains
  # We safeguard and only run this task if it is needed. So if it is being run,
  # it does enable the repo and thus should show changed.
  changed_when: true
  when:
    - 'ansible_distribution == "RedHat"'
    - 'ansible_distribution_major_version | int == 8 or ansible_distribution_major_version | int == 9'
    - '"0" in subscription_manager_output.stdout'

- name: 'Install package epel-release'
  ansible.builtin.package:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: 'present'
  when:
    - 'ansible_distribution == "RedHat"'
  notify:
    - 'Install epel-release key from /etc/pki/rpm-gpg/'
    - "Run 'yum makecache fast'"
    - "Run 'dnf makecache'"

- name: 'Flush handlers'
  ansible.builtin.meta: flush_handlers
