---
# RedHat_install_epel-release/handlers/main.yml

- name: "run 'yum makecache fast'"
  command: "yum makecache fast"
  when:
    - 'ansible_distribution == "RedHat"'
    - 'ansible_distribution_major_version == "7"'

- name: "run 'dnf makecache'"
  command: "dnf makecache"
  when:
    - 'ansible_distribution == "RedHat"'
    - 'ansible_distribution_major_version == "8"'
