---
# RedHat_install_epel-release/handlers/main.yml

- name: "Run 'yum makecache fast'"
  ansible.builtin.command: "yum makecache fast"
  when:
    - 'ansible_distribution == "RedHat"'
    - 'ansible_distribution_major_version | int == 7'

- name: "Run 'dnf makecache'"
  ansible.builtin.command: "dnf makecache"
  when:
    - 'ansible_distribution == "RedHat"'
    - 'ansible_distribution_major_version | int >= 8'
